import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en' | 'pt' | 'qu' | 'ay';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  es: {
    // Navigation
    'nav.report': 'Reportar',
    'nav.learn': 'Aprender',
    'nav.profile': 'Perfil',
    'nav.dashboard': 'Dashboard',
    'nav.editor': 'Editor',

    // Report Form
    'report.title': 'Reporte De Avistamiento',
    'report.subtitle': 'Tu contribución ayuda a la conservación',
    'report.identification': 'Identificación',
    'report.select_animal': 'Selecciona el animal que avistaste',
    'report.jaguar': 'Jaguar',
    'report.jaguar_desc': 'MANCHAS EN ROSETA',
    'report.puma': 'Puma',
    'report.puma_desc': 'COLOR UNIFORME',
    'report.other': 'Otro animal',
    'report.other_desc': 'ESPECIFICAR CUÁL',
    'report.unknown': 'No sé',
    'report.unknown_desc': 'SIN IDENTIFICAR',
    'report.reporting': 'Reportando',
    'report.change': 'Cambiar',
    'report.specify': 'Especificar animal',
    'report.specify_placeholder': 'Escribe el nombre del animal...',
    'report.location': 'Ubicación',
    'report.location_desc': 'Coordenadas GPS automáticas',
    'report.evidence': 'Evidencia',
    'report.evidence_desc': 'Sube una foto clara',
    'report.take_photo': 'Tomar Foto',
    'report.upload_photo': 'Subir de Galería',
    'report.send': 'Enviar Reporte',
    'report.sending': 'Enviando...',
    'report.success_title': '¡Reporte Enviado!',
    'report.success_desc': 'Gracias por contribuir a la conservación.',
    'report.new_report': 'Nuevo Reporte',
    'report.error_location': 'Error obteniendo ubicación',
    'report.error_camera': 'Error accediendo a la cámara',

    // Profile
    'profile.title': 'Mi Perfil',
    'profile.level': 'Nivel',
    'profile.points': 'Puntos',
    'profile.redeem': 'Canjear',
    'profile.redeem_goal': '¡Meta alcanzada!',
    'profile.redeem_missing': 'Faltan {points} puntos',
    'profile.reports_30_days': 'Reportes Realizados (30 días)',
    'profile.settings': 'Configuración',
    'profile.edit_profile': 'Editar Perfil',
    'profile.avatar': 'Tu Avatar',
    'profile.personal_info': 'Información Personal',
    'profile.full_name': 'Nombre Completo',
    'profile.contact': 'Correo / Contacto',
    'profile.change_password': 'Cambiar Contraseña',
    'profile.preferences': 'Preferencias',
    'profile.dark_mode': 'Modo Oscuro',
    'profile.language': 'Idioma',
    'profile.save_changes': 'Guardar Cambios',
    'profile.cancel': 'Cancelar',
    'profile.confirm_redeem_title': 'Confirmar Canje',
    'profile.confirm_redeem_desc': '¿Estás seguro de que deseas canjear 150 puntos por una recompensa?',
    'profile.redeem_success_title': '¡Solicitud Recibida!',
    'profile.redeem_success_desc': 'Se estará evaluando la calidad de sus puntos. Nos comunicaremos pronto a través de la información de contacto proporcionada.',
    'profile.understood': 'Entendido',
    
    // Profile Errors & Success
    'profile.error_redeem': 'Error al canjear',
    'profile.success_update': 'Perfil actualizado correctamente',
    'profile.error_update': 'Error al guardar cambios',
    'profile.error_password_fields': 'Completa los campos de nueva contraseña',
    'profile.error_password_match': 'Las contraseñas nuevas no coinciden',
    'profile.error_password_length': 'La nueva contraseña debe tener al menos 6 caracteres',
    'profile.success_password': 'Contraseña actualizada correctamente',
    'profile.error_no_session': 'No hay sesión activa',
    'profile.error_password_update': 'Error al actualizar contraseña',
    
    // Profile UI
    'profile.my_points': 'Mis Puntos',
    'profile.request_received': '¡Solicitud Recibida!',
    'profile.request_received_desc': 'Se estará evaluando la calidad de sus puntos. Nos comunicaremos pronto.',
    'profile.tutorial': 'Ver Tutorial',
    'profile.logout': 'Cerrar Sesión',
    'profile.support': 'Soporte',
    'profile.history_title': 'Últimos 30 días',
    'profile.no_reports': 'No hay reportes recientes.',
    'profile.new_password': 'Nueva contraseña',
    'profile.confirm_password': 'Confirmar nueva contraseña',
    'profile.save': 'Guardar',

    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.export_data': 'Exportar Datos',
    'admin.export_excel': 'Exportar a Excel',
    'admin.export_excel_history': 'Excel: Histórico',
    'admin.export_csv_history': 'CSV: Histórico',
    'admin.export_excel_30': 'Excel: 30 Días',
    'admin.export_csv_30': 'CSV: 30 Días',
    'admin.export_excel_verified': 'Excel: Verificados',
    'admin.export_csv_verified': 'CSV: Verificados',
    'admin.total_reports': 'Reportes Totales',
    'admin.verified_reports': 'Reportes Verificados',
    'admin.pending_redemptions': 'Canjes Pendientes',
    'admin.users': 'Usuarios',
    'admin.messages': 'Mensajes',
    'admin.frequency_type': 'Frecuencia por Especie (30d)',
    'admin.heatmap_history': 'Mapa de Calor (Histórico)',
    'admin.heatmap_30': 'Mapa de Calor (Últimos 30 días)',
    'admin.pending_reports': 'Reportes Pendientes',
    'admin.verified_reports_30': 'Reportes Verificados (30d)',
    'admin.redemption_requests': 'Solicitudes de Canje',
    'admin.user_management': 'Gestión de Usuarios',
    'admin.report_history': 'Historial de Reportes',
    'admin.view_pending': 'Ver Pendientes',
    'admin.make_admin': 'Hacer Admin',
    'admin.remove_admin': 'Quitar Admin',
    'admin.approve': 'Aprobar',
    'admin.reject': 'Rechazar',
    'admin.status_pending': 'Pendiente',
    'admin.status_approved': 'Aprobado',
    'admin.status_rejected': 'Rechazado',
    'admin.status_verified': 'Verificado',
    'admin.status_denied': 'Denegado',
    'admin.user': 'Usuario',
    'admin.contact': 'Contacto',
    'admin.date': 'Fecha',
    'admin.notes': 'Notas',
    'admin.anonymous': 'Anónimo',

    // Onboarding
    'onboarding.skip': 'Omitir',
    'onboarding.next': 'Siguiente',
    'onboarding.start': 'Empezar ahora',
    'onboarding.slide1_title': 'Reporta en segundos',
    'onboarding.slide1_desc': 'Toca la categoría que mejor describa lo que viste en el campo.',
    'onboarding.slide2_title': 'Ubicación y Evidencia',
    'onboarding.slide2_desc': 'El GPS se activa solo. Toma una foto clara para validar tu reporte.',
    'onboarding.slide_tracks_title': 'Reporte de Huellas',
    'onboarding.slide_tracks_desc': 'Si encuentras una huella, coloca tu mano cerca para tener un punto de referencia en la foto.',
    'onboarding.slide3_title': '¿Sin señal?\nNo hay problema.',
    'onboarding.slide3_desc': 'Coex5.0 guarda tus reportes y los envía automáticamente cuando recuperes internet.',
    'onboarding.slide4_title': 'Gana Beneficios',
    'onboarding.slide4_desc': 'Cada reporte verificado te suma 10 puntos. ¡Llega a 150 y el Especialista te dará recompensas para seguir fomentando el cuidado ambiental!',
    'onboarding.reward_label': 'Recompensa del Especialista',
    'onboarding.points_label': 'pts',
    'onboarding.offline_label': 'Sin conexión',
    'onboarding.saved_label': 'Guardado localmente',
    
    // Learn Section
    'learn.title': 'APRENDE CON COEX5.0',
    'learn.subtitle': 'Aprende sobre prevención, rastros y normativas.',
    'learn.search_placeholder': 'Buscar guías, videos, consejos...',
    'learn.categories': 'Categorías',
    'learn.no_guides': 'Aún no hay publicaciones en esta categoría.',
    'learn.no_saved': 'No tienes publicaciones guardadas.',
    'learn.saved_offline': 'Guardados (Offline)',
    'learn.saved_count': '{count} publicaciones',
    'learn.share': 'Compartir',
    'learn.consult': 'Consultar',
    'learn.contact_specialist': 'Contactar Especialista',
    'learn.your_name': 'Tu Nombre',
    'learn.contact_info': 'Contacto',
    'learn.reference': 'Referencia',
    'learn.query_label': '¿Cuál es tu consulta?',
    'learn.query_placeholder': 'Escribe tu duda aquí...',
    'learn.send_query': 'Enviar Consulta',
    'learn.sending': 'Enviando...',
    'learn.read_time': '{time} min',
    'learn.attachments': 'Archivos Adjuntos',
    'learn.video': 'Video',
    'learn.image': 'Imagen',
    'learn.file': 'Archivo',
    'learn.link': 'Enlace',
    'learn.offline_warning': 'Sin conexión: Solo se muestran guías guardadas.',
    'learn.save_for_offline': 'Guardar para leer sin internet',
    'learn.saved_success': 'Guía guardada para leer sin conexión',
    'learn.removed_success': 'Guía eliminada de tus guardados',

    // Editor Section
    'editor.title': 'Editor de Contenido',
    'editor.groups': 'Grupos',
    'editor.guides': 'Guías',
    'editor.create_group': 'Crear Nuevo Grupo',
    'editor.edit_group': 'Editar Grupo',
    'editor.group_name': 'Nombre del Grupo',
    'editor.group_icon': 'Icono del Grupo',
    'editor.save': 'Guardar',
    'editor.cancel': 'Cancelar',
    'editor.create_guide': 'Crear Nueva Guía',
    'editor.edit_guide': 'Editar Guía',
    'editor.guide_title': 'Título de la Guía',
    'editor.guide_subtitle': 'Subtítulo / Descripción Corta',
    'editor.guide_group': 'Grupo / Categoría',
    'editor.guide_read_time': 'Tiempo de Lectura (min)',
    'editor.guide_image': 'URL de Imagen de Portada',
    'editor.guide_video': 'URL de Video (Youtube/Vimeo)',
    'editor.guide_content': 'Contenido de la Guía',
    'editor.preview': 'Vista Previa',
    'editor.edit': 'Editar Contenido',
    'editor.publish': 'Publicar Guía',
    'editor.delete_confirm': '¿Estás seguro de eliminar esto?',
    'editor.no_groups': 'No hay grupos creados.',
    'editor.no_guides': 'No hay guías publicadas.',
    'editor.add_video_url': 'Agregar URL de Video',
    'editor.add_image_url': 'Agregar URL de Imagen',
    'editor.add_file': 'Adjuntar Archivo',
    'editor.add_link': 'Agregar Enlace',
  },
  en: {
    'nav.report': 'Report',
    'nav.learn': 'Learn',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'nav.editor': 'Editor',

    'report.title': 'Sighting Report',
    'report.subtitle': 'Your contribution helps conservation',
    'report.identification': 'Identification',
    'report.select_animal': 'Select the animal you sighted',
    'report.jaguar': 'Jaguar',
    'report.jaguar_desc': 'ROSETTE SPOTS',
    'report.puma': 'Puma',
    'report.puma_desc': 'UNIFORM COLOR',
    'report.other': 'Other animal',
    'report.other_desc': 'SPECIFY WHICH',
    'report.unknown': 'I don\'t know',
    'report.unknown_desc': 'UNIDENTIFIED',
    'report.reporting': 'Reporting',
    'report.change': 'Change',
    'report.specify': 'Specify animal',
    'report.specify_placeholder': 'Type the animal name...',
    'report.location': 'Location',
    'report.location_desc': 'Automatic GPS coordinates',
    'report.evidence': 'Evidence',
    'report.evidence_desc': 'Upload a clear photo',
    'report.take_photo': 'Take Photo',
    'report.upload_photo': 'Upload from Gallery',
    'report.send': 'Send Report',
    'report.sending': 'Sending...',
    'report.success_title': 'Report Sent!',
    'report.success_desc': 'Thank you for contributing to conservation.',
    'report.new_report': 'New Report',
    'report.error_location': 'Error getting location',
    'report.error_camera': 'Error accessing camera',

    'profile.title': 'My Profile',
    'profile.level': 'Level',
    'profile.points': 'Points',
    'profile.redeem': 'Redeem',
    'profile.redeem_goal': 'Goal reached!',
    'profile.redeem_missing': '{points} points missing',
    'profile.reports_30_days': 'Reports Made (30 days)',
    'profile.settings': 'Settings',
    'profile.edit_profile': 'Edit Profile',
    'profile.avatar': 'Your Avatar',
    'profile.personal_info': 'Personal Information',
    'profile.full_name': 'Full Name',
    'profile.contact': 'Email / Contact',
    'profile.change_password': 'Change Password',
    'profile.preferences': 'Preferences',
    'profile.dark_mode': 'Dark Mode',
    'profile.language': 'Language',
    'profile.save_changes': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.confirm_redeem_title': 'Confirm Redemption',
    'profile.confirm_redeem_desc': 'Are you sure you want to redeem 150 points for a reward?',
    'profile.redeem_success_title': 'Request Received!',
    'profile.redeem_success_desc': 'We will be evaluating the quality of your points. We will contact you soon via the contact information provided.',
    'profile.understood': 'Understood',
    
    'profile.error_redeem': 'Error redeeming',
    'profile.success_update': 'Profile updated successfully',
    'profile.error_update': 'Error saving changes',
    'profile.error_password_fields': 'Complete the new password fields',
    'profile.error_password_match': 'New passwords do not match',
    'profile.error_password_length': 'New password must be at least 6 characters',
    'profile.success_password': 'Password updated successfully',
    'profile.error_no_session': 'No active session',
    'profile.error_password_update': 'Error updating password',
    
    'profile.my_points': 'My Points',
    'profile.request_received': 'Request Received!',
    'profile.request_received_desc': 'We will be evaluating the quality of your points. We will contact you soon.',
    'profile.tutorial': 'View Tutorial',
    'profile.logout': 'Log Out',
    'profile.support': 'Support',
    'profile.history_title': 'Last 30 days',
    'profile.no_reports': 'No recent reports.',
    'profile.new_password': 'New password',
    'profile.confirm_password': 'Confirm new password',
    'profile.save': 'Save',

    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.export_data': 'Export Data',
    'admin.export_excel': 'Export to Excel',
    'admin.export_excel_history': 'Excel: History',
    'admin.export_csv_history': 'CSV: History',
    'admin.export_excel_30': 'Excel: 30 Days',
    'admin.export_csv_30': 'CSV: 30 Days',
    'admin.export_excel_verified': 'Excel: Verified',
    'admin.export_csv_verified': 'CSV: Verified',
    'admin.total_reports': 'Total Reports',
    'admin.verified_reports': 'Verified Reports',
    'admin.pending_redemptions': 'Pending Redemptions',
    'admin.users': 'Users',
    'admin.messages': 'Messages',
    'admin.frequency_type': 'Frequency by Species (30d)',
    'admin.heatmap_history': 'Heatmap (History)',
    'admin.heatmap_30': 'Heatmap (Last 30 days)',
    'admin.pending_reports': 'Pending Reports',
    'admin.verified_reports_30': 'Verified Reports (30d)',
    'admin.redemption_requests': 'Redemption Requests',
    'admin.user_management': 'User Management',
    'admin.report_history': 'Report History',
    'admin.view_pending': 'View Pending',
    'admin.make_admin': 'Make Admin',
    'admin.remove_admin': 'Remove Admin',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.status_pending': 'Pending',
    'admin.status_approved': 'Approved',
    'admin.status_rejected': 'Rejected',
    'admin.status_verified': 'Verified',
    'admin.status_denied': 'Denied',
    'admin.user': 'User',
    'admin.contact': 'Contact',
    'admin.date': 'Date',
    'admin.notes': 'Notes',
    'admin.anonymous': 'Anonymous',

    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.start': 'Start now',
    'onboarding.slide1_title': 'Report in seconds',
    'onboarding.slide1_desc': 'Tap the category that best describes what you saw in the field.',
    'onboarding.slide2_title': 'Location and Evidence',
    'onboarding.slide2_desc': 'GPS activates automatically. Take a clear photo to validate your report.',
    'onboarding.slide_tracks_title': 'Track Reports',
    'onboarding.slide_tracks_desc': 'If you find a track, place your hand near it to provide a reference point in the photo.',
    'onboarding.slide3_title': 'No signal?\nNo problem.',
    'onboarding.slide3_desc': 'Coex5.0 saves your reports and sends them automatically when you regain internet.',
    'onboarding.slide4_title': 'Earn Benefits',
    'onboarding.slide4_desc': 'Each verified report adds 10 points. Reach 150 and the Specialist will give you rewards to continue encouraging environmental care!',
    'onboarding.reward_label': 'Specialist Reward',
    'onboarding.points_label': 'pts',
    'onboarding.offline_label': 'Offline',
    'onboarding.saved_label': 'Saved locally',

    // Learn Section
    'learn.title': 'LEARN WITH COEX5.0',
    'learn.subtitle': 'Learn about prevention, tracks, and regulations.',
    'learn.search_placeholder': 'Search guides, videos, tips...',
    'learn.categories': 'Categories',
    'learn.no_guides': 'No publications in this category yet.',
    'learn.no_saved': 'You have no saved publications.',
    'learn.saved_offline': 'Saved (Offline)',
    'learn.saved_count': '{count} publications',
    'learn.share': 'Share',
    'learn.consult': 'Consult',
    'learn.contact_specialist': 'Contact Specialist',
    'learn.your_name': 'Your Name',
    'learn.contact_info': 'Contact',
    'learn.reference': 'Reference',
    'learn.query_label': 'What is your query?',
    'learn.query_placeholder': 'Write your question here...',
    'learn.send_query': 'Send Query',
    'learn.sending': 'Sending...',
    'learn.read_time': '{time} min',
    'learn.attachments': 'Attached Files',
    'learn.video': 'Video',
    'learn.image': 'Image',
    'learn.file': 'File',
    'learn.link': 'Link',
    'learn.offline_warning': 'Offline: Only saved guides are shown.',
    'learn.save_for_offline': 'Save to read without internet',
    'learn.saved_success': 'Guide saved for offline reading',
    'learn.removed_success': 'Guide removed from your saved list',

    // Editor Section
    'editor.title': 'Content Editor',
    'editor.groups': 'Groups',
    'editor.guides': 'Guides',
    'editor.create_group': 'Create New Group',
    'editor.edit_group': 'Edit Group',
    'editor.group_name': 'Group Name',
    'editor.group_icon': 'Group Icon',
    'editor.save': 'Save',
    'editor.cancel': 'Cancel',
    'editor.create_guide': 'Create New Guide',
    'editor.edit_guide': 'Edit Guide',
    'editor.guide_title': 'Guide Title',
    'editor.guide_subtitle': 'Subtitle / Short Description',
    'editor.guide_group': 'Group / Category',
    'editor.guide_read_time': 'Read Time (min)',
    'editor.guide_image': 'Cover Image URL',
    'editor.guide_video': 'Video URL (Youtube/Vimeo)',
    'editor.guide_content': 'Guide Content',
    'editor.preview': 'Preview',
    'editor.edit': 'Edit Content',
    'editor.publish': 'Publish Guide',
    'editor.delete_confirm': 'Are you sure you want to delete this?',
    'editor.no_groups': 'No groups created.',
    'editor.no_guides': 'No guides published.',
    'editor.add_video_url': 'Add Video URL',
    'editor.add_image_url': 'Add Image URL',
    'editor.add_file': 'Attach File',
    'editor.add_link': 'Add Link',
  },
  pt: {
    'nav.report': 'Relatar',
    'nav.learn': 'Aprender',
    'nav.profile': 'Perfil',
    'nav.dashboard': 'Painel',
    'nav.editor': 'Editor',

    'report.title': 'Relatório de Avistamento',
    'report.subtitle': 'Sua contribuição ajuda na conservação',
    'report.identification': 'Identificação',
    'report.select_animal': 'Selecione o animal que você avistou',
    'report.jaguar': 'Onça-pintada',
    'report.jaguar_desc': 'MANCHAS EM ROSETA',
    'report.puma': 'Puma',
    'report.puma_desc': 'COR UNIFORME',
    'report.other': 'Outro animal',
    'report.other_desc': 'ESPECIFICAR QUAL',
    'report.unknown': 'Não sei',
    'report.unknown_desc': 'NÃO IDENTIFICADO',
    'report.reporting': 'Relatando',
    'report.change': 'Alterar',
    'report.specify': 'Especificar animal',
    'report.specify_placeholder': 'Digite o nome do animal...',
    'report.location': 'Localização',
    'report.location_desc': 'Coordenadas GPS automáticas',
    'report.evidence': 'Evidência',
    'report.evidence_desc': 'Envie uma foto clara',
    'report.take_photo': 'Tirar Foto',
    'report.upload_photo': 'Carregar da Galeria',
    'report.send': 'Enviar Relatório',
    'report.sending': 'Enviando...',
    'report.success_title': 'Relatório Enviado!',
    'report.success_desc': 'Obrigado por contribuir para a conservação.',
    'report.new_report': 'Novo Relatório',
    'report.error_location': 'Erro ao obter localização',
    'report.error_camera': 'Erro ao acessar a câmera',

    'profile.title': 'Meu Perfil',
    'profile.level': 'Nível',
    'profile.points': 'Pontos',
    'profile.redeem': 'Resgatar',
    'profile.redeem_goal': 'Meta alcançada!',
    'profile.redeem_missing': 'Faltam {points} pontos',
    'profile.reports_30_days': 'Relatórios Realizados (30 dias)',
    'profile.settings': 'Configurações',
    'profile.edit_profile': 'Editar Perfil',
    'profile.avatar': 'Seu Avatar',
    'profile.personal_info': 'Informações Pessoais',
    'profile.full_name': 'Nome Completo',
    'profile.contact': 'Email / Contato',
    'profile.change_password': 'Alterar Senha',
    'profile.preferences': 'Preferências',
    'profile.dark_mode': 'Modo Escuro',
    'profile.language': 'Idioma',
    'profile.save_changes': 'Salvar Alterações',
    'profile.cancel': 'Cancelar',
    'profile.confirm_redeem_title': 'Confirmar Resgate',
    'profile.confirm_redeem_desc': 'Tem certeza de que deseja resgatar 150 pontos por uma recompensa?',
    'profile.redeem_success_title': 'Solicitação Recebida!',
    'profile.redeem_success_desc': 'Estaremos avaliando a qualidade dos seus pontos. Entraremos em contato em breve através das informações de contato fornecidas.',
    'profile.understood': 'Entendido',
    
    'profile.error_redeem': 'Erro ao resgatar',
    'profile.success_update': 'Perfil atualizado com sucesso',
    'profile.error_update': 'Erro ao salvar alterações',
    'profile.error_password_fields': 'Preencha os campos da nova senha',
    'profile.error_password_match': 'As novas senhas não coincidem',
    'profile.error_password_length': 'A nova senha deve ter pelo menos 6 caracteres',
    'profile.success_password': 'Senha atualizada com sucesso',
    'profile.error_no_session': 'Nenhuma sessão ativa',
    'profile.error_password_update': 'Erro ao atualizar a senha',
    
    'profile.my_points': 'Meus Pontos',
    'profile.request_received': 'Solicitação Recebida!',
    'profile.request_received_desc': 'Estaremos avaliando a qualidade dos seus pontos. Entraremos em contato em breve.',
    'profile.tutorial': 'Ver Tutorial',
    'profile.logout': 'Sair',
    'profile.support': 'Suporte',
    'profile.history_title': 'Últimos 30 dias',
    'profile.no_reports': 'Nenhum relatório recente.',
    'profile.new_password': 'Nova senha',
    'profile.confirm_password': 'Confirmar nova senha',
    'profile.save': 'Salvar',

    // Admin Dashboard
    'admin.dashboard': 'Painel',
    'admin.export_data': 'Exportar Dados',
    'admin.export_excel': 'Exportar para Excel',
    'admin.export_excel_history': 'Excel: Histórico',
    'admin.export_csv_history': 'CSV: Histórico',
    'admin.export_excel_30': 'Excel: 30 Dias',
    'admin.export_csv_30': 'CSV: 30 Dias',
    'admin.export_excel_verified': 'Excel: Verificados',
    'admin.export_csv_verified': 'CSV: Verificados',
    'admin.total_reports': 'Relatórios Totais',
    'admin.verified_reports': 'Relatórios Verificados',
    'admin.pending_redemptions': 'Resgates Pendentes',
    'admin.users': 'Usuários',
    'admin.messages': 'Mensagens',
    'admin.frequency_type': 'Frequência por Espécie (30d)',
    'admin.heatmap_history': 'Mapa de Calor (Histórico)',
    'admin.heatmap_30': 'Mapa de Calor (Últimos 30 dias)',
    'admin.pending_reports': 'Relatórios Pendentes',
    'admin.verified_reports_30': 'Relatórios Verificados (30d)',
    'admin.redemption_requests': 'Solicitações de Resgate',
    'admin.user_management': 'Gestão de Usuários',
    'admin.report_history': 'Histórico de Relatórios',
    'admin.view_pending': 'Ver Pendentes',
    'admin.make_admin': 'Tornar Admin',
    'admin.remove_admin': 'Remover Admin',
    'admin.approve': 'Aprovar',
    'admin.reject': 'Rejeitar',
    'admin.status_pending': 'Pendente',
    'admin.status_approved': 'Aprovado',
    'admin.status_rejected': 'Rejeitado',
    'admin.status_verified': 'Verificado',
    'admin.status_denied': 'Negado',
    'admin.user': 'Usuário',
    'admin.contact': 'Contato',
    'admin.date': 'Data',
    'admin.notes': 'Notas',
    'admin.anonymous': 'Anônimo',

    'onboarding.skip': 'Pular',
    'onboarding.next': 'Próximo',
    'onboarding.start': 'Começar agora',
    'onboarding.slide1_title': 'Relate em segundos',
    'onboarding.slide1_desc': 'Toque na categoria que melhor descreve o que você viu no campo.',
    'onboarding.slide2_title': 'Localização e Evidência',
    'onboarding.slide2_desc': 'O GPS é ativado automaticamente. Tire uma foto clara para validar seu relatório.',
    'onboarding.slide3_title': 'Sem sinal?\nSem problemas.',
    'onboarding.slide3_desc': 'O Coex5.0 salva seus relatórios e os envia automaticamente quando você recuperar a internet.',
    'onboarding.slide4_title': 'Ganhe Benefícios',
    'onboarding.slide4_desc': 'Cada relatório verificado adiciona 10 pontos. Chegue a 150 e o Especialista lhe dará recompensas para continuar incentivando o cuidado ambiental!',
    'onboarding.reward_label': 'Recompensa do Especialista',
    'onboarding.points_label': 'pts',
    'onboarding.offline_label': 'Sem conexão',
    'onboarding.saved_label': 'Salvo localmente',

    // Learn Section
    'learn.title': 'APRENDA COM COEX5.0',
    'learn.subtitle': 'Aprenda sobre prevenção, rastros e regulamentações.',
    'learn.search_placeholder': 'Buscar guias, vídeos, dicas...',
    'learn.categories': 'Categorias',
    'learn.no_guides': 'Ainda não há publicações nesta categoria.',
    'learn.no_saved': 'Você não tem publicações salvas.',
    'learn.saved_offline': 'Salvos (Offline)',
    'learn.saved_count': '{count} publicações',
    'learn.share': 'Compartilhar',
    'learn.consult': 'Consultar',
    'learn.contact_specialist': 'Contatar Especialista',
    'learn.your_name': 'Seu Nome',
    'learn.contact_info': 'Contato',
    'learn.reference': 'Referência',
    'learn.query_label': 'Qual é a sua dúvida?',
    'learn.query_placeholder': 'Escreva sua dúvida aqui...',
    'learn.send_query': 'Enviar Consulta',
    'learn.sending': 'Enviando...',
    'learn.read_time': '{time} min',
    'learn.attachments': 'Arquivos Anexados',
    'learn.video': 'Vídeo',
    'learn.image': 'Imagem',
    'learn.file': 'Arquivo',
    'learn.link': 'Link',
    'learn.offline_warning': 'Offline: Apenas guias salvos são mostrados.',
    'learn.save_for_offline': 'Salvar para ler sem internet',
    'learn.saved_success': 'Guia salvo para leitura offline',
    'learn.removed_success': 'Guia removido da sua lista de salvos',

    // Editor Section
    'editor.title': 'Editor de Conteúdo',
    'editor.groups': 'Grupos',
    'editor.guides': 'Guias',
    'editor.create_group': 'Criar Novo Grupo',
    'editor.edit_group': 'Editar Grupo',
    'editor.group_name': 'Nome do Grupo',
    'editor.group_icon': 'Ícone do Grupo',
    'editor.save': 'Salvar',
    'editor.cancel': 'Cancelar',
    'editor.create_guide': 'Criar Nova Guia',
    'editor.edit_guide': 'Editar Guia',
    'editor.guide_title': 'Título da Guia',
    'editor.guide_subtitle': 'Subtítulo / Descrição Curta',
    'editor.guide_group': 'Grupo / Categoria',
    'editor.guide_read_time': 'Tempo de Leitura (min)',
    'editor.guide_image': 'URL da Imagem de Capa',
    'editor.guide_video': 'URL do Vídeo (Youtube/Vimeo)',
    'editor.guide_content': 'Conteúdo da Guia',
    'editor.preview': 'Visualização',
    'editor.publish': 'Publicar Guia',
    'editor.delete_confirm': 'Tem certeza que deseja excluir isso?',
    'editor.no_groups': 'Nenhum grupo criado.',
    'editor.no_guides': 'Nenhuma guia publicada.',
    'editor.add_video_url': 'Adicionar URL do Vídeo',
    'editor.add_image_url': 'Adicionar URL da Imagem',
    'editor.add_file': 'Anexar Arquivo',
    'editor.add_link': 'Adicionar Link',
  },
  qu: {
    'nav.report': 'Willay',
    'nav.learn': 'Yachay',
    'nav.profile': 'Kawsay',
    'nav.dashboard': 'Dashboard',
    'nav.editor': 'Editor',

    'report.title': 'Uywa Rikuy Willay',
    'report.subtitle': 'Yanapaykuykiqa ancha allinmi',
    'report.identification': 'Riqsiy',
    'report.select_animal': 'Mayqen uywatam rikurqanki',
    'report.jaguar': 'Uturunku',
    'report.jaguar_desc': 'MURUYUQ',
    'report.puma': 'Puma',
    'report.puma_desc': 'CH\'ULLA LLIMPI',
    'report.other': 'Huk uywa',
    'report.other_desc': 'MAYQEN KASQANTA WILLAY',
    'report.unknown': 'Manam yachanichu',
    'report.unknown_desc': 'MANA RIQSISQA',
    'report.reporting': 'Willachkan',
    'report.change': 'Tikray',
    'report.specify': 'Uywa sutinta qillqay',
    'report.specify_placeholder': 'Uywa sutinta qillqay...',
    'report.location': 'Tiyay',
    'report.location_desc': 'GPS kikinmanta',
    'report.evidence': 'Qawachiy',
    'report.evidence_desc': 'Huk fotota churay',
    'report.take_photo': 'Fotota Tomay',
    'report.upload_photo': 'Galeriamanta Churay',
    'report.send': 'Willayta Kachay',
    'report.sending': 'Kachachkan...',
    'report.success_title': '¡Willay Kachasqa!',
    'report.success_desc': 'Pachamamata waqaychaypi yanapasqaykimanta.',
    'report.new_report': 'Musuq Willay',
    'report.error_location': 'Tiyayta mana tarinchu',
    'report.error_camera': 'Camarata mana kichanchu',

    'profile.title': 'Ñuqaq Kawsayniy',
    'profile.level': 'Nivel',
    'profile.points': 'Puntos',
    'profile.redeem': 'Tikray',
    'profile.redeem_goal': '¡Aypasqa!',
    'profile.redeem_missing': '{points} puntos faltan',
    'profile.reports_30_days': 'Willaykuna (30 p\'unchaw)',
    'profile.settings': 'Allichay',
    'profile.edit_profile': 'Kawsayta Allichay',
    'profile.avatar': 'Qampa Avatar',
    'profile.personal_info': 'Kikiykiq Willayniyki',
    'profile.full_name': 'Suti',
    'profile.contact': 'Correo / Willay',
    'profile.change_password': 'Contraseñata Tikray',
    'profile.preferences': 'Munaykuna',
    'profile.dark_mode': 'Tuta Modo',
    'profile.language': 'Simi',
    'profile.save_changes': 'Tikraykunata Waqaychay',
    'profile.cancel': 'Ama',
    'profile.confirm_redeem_title': 'Tikrayta Munankichu',
    'profile.confirm_redeem_desc': '¿Munankichu 150 puntosniykita tikrayta?',
    'profile.redeem_success_title': '¡Mañakuy Chaskisqa!',
    'profile.redeem_success_desc': 'Puntosniykita qawarisayku. Pisi tiempollamanta willasaykiku.',
    'profile.understood': 'Entiendi',
    
    'profile.error_redeem': 'Mana tikrayta atinchu',
    'profile.success_update': 'Kawsay allichasqa',
    'profile.error_update': 'Mana waqaychayta atinchu',
    'profile.error_password_fields': 'Musuq contraseñata qillqay',
    'profile.error_password_match': 'Contraseñakuna mana tupanichu',
    'profile.error_password_length': 'Contraseñaqa 6 letrayuq kanan',
    'profile.success_password': 'Contraseña tikrasqa',
    'profile.error_no_session': 'Mana sesión kanchu',
    'profile.error_password_update': 'Mana contraseñata tikrayta atinchu',
    
    'profile.my_points': 'Puntosniy',
    'profile.request_received': '¡Mañakuy Chaskisqa!',
    'profile.request_received_desc': 'Puntosniykita qawarisayku. Willasaykiku.',
    'profile.tutorial': 'Tutorial Qaway',
    'profile.logout': 'Lluqsiy',
    'profile.support': 'Yanapay',
    'profile.history_title': '30 p\'unchaw',
    'profile.no_reports': 'Mana willaykuna kanchu.',
    'profile.new_password': 'Musuq contraseña',
    'profile.confirm_password': 'Musuq contraseña takyachiy',
    'profile.save': 'Waqaychay',

    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.export_data': 'Willaykuna Exportay',
    'admin.export_excel': 'Excelman Exportay',
    'admin.export_excel_history': 'Excel: Ñawpaq',
    'admin.export_csv_history': 'CSV: Ñawpaq',
    'admin.export_excel_30': 'Excel: 30 P\'unchaw',
    'admin.export_csv_30': 'CSV: 30 P\'unchaw',
    'admin.export_excel_verified': 'Excel: Chiqanchasqa',
    'admin.export_csv_verified': 'CSV: Chiqanchasqa',
    'admin.total_reports': 'Lliw Willaykuna',
    'admin.verified_reports': 'Chiqanchasqa Willaykuna',
    'admin.pending_redemptions': 'Tikraykuna Suyachkan',
    'admin.users': 'Ruraqkuna',
    'admin.messages': 'Willaykuna',
    'admin.frequency_type': 'Uywa Rikuy (30d)',
    'admin.heatmap_history': 'Q\'uñi Mapa (Ñawpaq)',
    'admin.heatmap_30': 'Q\'uñi Mapa (30 p\'unchaw)',
    'admin.pending_reports': 'Willaykuna Suyachkan',
    'admin.verified_reports_30': 'Chiqanchasqa (30d)',
    'admin.redemption_requests': 'Tikray Mañakuykuna',
    'admin.user_management': 'Ruraqkuna Kamachiy',
    'admin.report_history': 'Willaykuna Wiñay kawsay',
    'admin.view_pending': 'Suyachkaq Qaway',
    'admin.make_admin': 'Admin Ruray',
    'admin.remove_admin': 'Admin Qichuy',
    'admin.approve': 'Arí niy',
    'admin.reject': 'Mana niy',
    'admin.status_pending': 'Suyachkan',
    'admin.status_approved': 'Arí nisqa',
    'admin.status_rejected': 'Mana nisqa',
    'admin.status_verified': 'Chiqanchasqa',
    'admin.status_denied': 'Mana chaskisqa',
    'admin.user': 'Ruraq',
    'admin.contact': 'Willay',
    'admin.date': 'P\'unchaw',
    'admin.notes': 'Qillqaykuna',
    'admin.anonymous': 'Mana sutiyuq',

    'onboarding.skip': 'Pasay',
    'onboarding.next': 'Qatiq',
    'onboarding.start': 'Qallariy',
    'onboarding.slide1_title': 'Ratulla willay',
    'onboarding.slide1_desc': 'Mayqen uywatam rikurqanki, chayta toqay.',
    'onboarding.slide2_title': 'Tiyay hinaspa Qawachiy',
    'onboarding.slide2_desc': 'GPS kikinmanta kichakun. Huk fotota tomay.',
    'onboarding.slide3_title': '¿Mana señal kanchu?\nManam sasachakuymanchu.',
    'onboarding.slide3_desc': 'Coex5.0 willayniykita waqaychan hinaspa internet kaptin kachan.',
    'onboarding.slide4_title': 'Gana Beneficios',
    'onboarding.slide4_desc': 'Sapa willay 10 puntosta qusunki. 150 aypaptiykiqa, Especialista regalota qusunki!',
    'onboarding.reward_label': 'Especialista Regalo',
    'onboarding.points_label': 'pts',
    'onboarding.offline_label': 'Mana internetwan',
    'onboarding.saved_label': 'Kaypi waqaychasqa',

    // Learn Section
    'learn.title': 'COEX5.0 WAN YACHAY',
    'learn.subtitle': 'Waqaychaymanta, yupikunaman hinaspa kamachiykunamanta yachay.',
    'learn.search_placeholder': 'Guíakuna, videokuna, yachaykuna maskay...',
    'learn.categories': 'Categoríakuna',
    'learn.no_guides': 'Manaraq kanchu kaypiqa.',
    'learn.no_saved': 'Manam waqaychasqayki kanchu.',
    'learn.saved_offline': 'Waqaychasqa (Offline)',
    'learn.saved_count': '{count} willaykuna',
    'learn.share': 'Rakiy',
    'learn.consult': 'Tapuy',
    'learn.contact_specialist': 'Especialistawan rimay',
    'learn.your_name': 'Sutiyki',
    'learn.contact_info': 'Willay',
    'learn.reference': 'Referencia',
    'learn.query_label': '¿Ima tapukuyniyki kachkan?',
    'learn.query_placeholder': 'Kaypi tapukuyniykita qillqay...',
    'learn.send_query': 'Tapuyta kachay',
    'learn.sending': 'Kachachkan...',
    'learn.read_time': '{time} min',
    'learn.attachments': 'Waqaychasqa Archivo',
    'learn.video': 'Video',
    'learn.image': 'Imagen',
    'learn.file': 'Archivo',
    'learn.link': 'Enlace',
    'learn.offline_warning': 'Offline: Waqaychasqallam qawakun.',
    'learn.save_for_offline': 'Internet mana kaptin leenapaq waqaychay',
    'learn.saved_success': 'Guía waqaychasqa internet mana kaptin leenapaq',
    'learn.removed_success': 'Guía waqaychasqaykimanta qichusqa',

    // Editor Section
    'editor.title': 'Willay Allichaq',
    'editor.groups': 'Grupokuna',
    'editor.guides': 'Guíakuna',
    'editor.create_group': 'Musuq Grupo Ruray',
    'editor.edit_group': 'Grupo Allichay',
    'editor.group_name': 'Grupo Suti',
    'editor.group_icon': 'Grupo Icono',
    'editor.save': 'Waqaychay',
    'editor.cancel': 'Ama',
    'editor.create_guide': 'Musuq Guía Ruray',
    'editor.edit_guide': 'Guía Allichay',
    'editor.guide_title': 'Guía Suti',
    'editor.guide_subtitle': 'Suti / Pisi Willay',
    'editor.guide_group': 'Grupo / Categoría',
    'editor.guide_read_time': 'Leenapaq Tiempo (min)',
    'editor.guide_image': 'Imagen URL',
    'editor.guide_video': 'Video URL (Youtube/Vimeo)',
    'editor.guide_content': 'Guía Willaynin',
    'editor.preview': 'Qaway',
    'editor.publish': 'Guía Publicay',
    'editor.delete_confirm': '¿Munankichu kayta qichuyta?',
    'editor.no_groups': 'Manam grupokuna kanchu.',
    'editor.no_guides': 'Manam guíakuna kanchu.',
    'editor.add_video_url': 'Video URL Churay',
    'editor.add_image_url': 'Imagen URL Churay',
    'editor.add_file': 'Archivo Churay',
    'editor.add_link': 'Enlace Churay',
  },
  ay: {
    'nav.report': 'Yatiyaña',
    'nav.learn': 'Yatiqaña',
    'nav.profile': 'Jakaña',
    'nav.dashboard': 'Dashboard',
    'nav.editor': 'Editor',

    'report.title': 'Uywa Uñjat Yatiyaña',
    'report.subtitle': 'Yanapt\'awimax wali askiwa',
    'report.identification': 'Uñt\'aña',
    'report.select_animal': 'Kawkir uywsa uñjta',
    'report.jaguar': 'Jaguar',
    'report.jaguar_desc': 'MURUNAKANI',
    'report.puma': 'Puma',
    'report.puma_desc': 'MA SAMINI',
    'report.other': 'Yaqha uywa',
    'report.other_desc': 'KAWKIRISA QILLQAÑA',
    'report.unknown': 'Janiw yatt\'ti',
    'report.unknown_desc': 'JAN UÑT\'ATA',
    'report.reporting': 'Yatiyaskta',
    'report.change': 'Turkaña',
    'report.specify': 'Uywa suti qillqaña',
    'report.specify_placeholder': 'Uywa suti qillqam...',
    'report.location': 'Kawkhansa',
    'report.location_desc': 'GPS kikinmanta',
    'report.evidence': 'Uñachayaña',
    'report.evidence_desc': 'Ma foto apsuñamawa',
    'report.take_photo': 'Foto Apsuña',
    'report.upload_photo': 'Galeria uchat Apsuña',
    'report.send': 'Yatiyaña Khitaña',
    'report.sending': 'Khitaskta...',
    'report.success_title': '¡Yatiyaña Khitata!',
    'report.success_desc': 'Pachamama arxatañataki yanapt\'awimata yuspagara.',
    'report.new_report': 'Machaq Yatiyaña',
    'report.error_location': 'Janiw jikxatkiti',
    'report.error_camera': 'Janiw camara jist\'arkiti',

    'profile.title': 'Nayan Jakañaja',
    'profile.level': 'Nivel',
    'profile.points': 'Puntos',
    'profile.redeem': 'Turkaña',
    'profile.redeem_goal': '¡Phuqhata!',
    'profile.redeem_missing': '{points} puntos falti',
    'profile.reports_30_days': 'Yatiyañanaka (30 uru)',
    'profile.settings': 'Askiachaña',
    'profile.edit_profile': 'Jakaña Askiachaña',
    'profile.avatar': 'Juman Avatar',
    'profile.personal_info': 'Juman Yatiyawinaka',
    'profile.full_name': 'Suti',
    'profile.contact': 'Correo / Yatiyaña',
    'profile.change_password': 'Contraseña Turkaña',
    'profile.preferences': 'Munañanaka',
    'profile.dark_mode': 'Ch\'amaka Modo',
    'profile.language': 'Aru',
    'profile.save_changes': 'Turkatanaka Imayaña',
    'profile.cancel': 'Janiwa',
    'profile.confirm_redeem_title': 'Turkaña Iyaw Saña',
    'profile.confirm_redeem_desc': '¿Cheqapuniw 150 puntos turkaña muntati?',
    'profile.redeem_success_title': '¡Mayiwi Katuqata!',
    'profile.redeem_success_desc': 'Puntos uñakipapxä. Juk\'a tiemputa yatiyapxäma.',
    'profile.understood': 'Entiendi',
    
    'profile.error_redeem': 'Janiw turkaña atiskiti',
    'profile.success_update': 'Jakaña askichata',
    'profile.error_update': 'Janiw imayaña atiskiti',
    'profile.error_password_fields': 'Machaq contraseña qillqam',
    'profile.error_password_match': 'Contraseñanakax janiw kikipkiti',
    'profile.error_password_length': 'Contraseñax 6 qillqaniñapawa',
    'profile.success_password': 'Contraseña turkata',
    'profile.error_no_session': 'Janiw sesión utjkiti',
    'profile.error_password_update': 'Janiw contraseña turkaña atiskiti',
    
    'profile.my_points': 'Puntosnaka',
    'profile.request_received': '¡Mayiwi Katuqata!',
    'profile.request_received_desc': 'Puntos uñakipapxä. Yatiyapxäma.',
    'profile.tutorial': 'Tutorial Uñjaña',
    'profile.logout': 'Mistuña',
    'profile.support': 'Yanapa',
    'profile.history_title': '30 uru',
    'profile.no_reports': 'Janiw yatiyawinaka utjkiti.',
    'profile.new_password': 'Machaq contraseña',
    'profile.confirm_password': 'Machaq contraseña iyaw saña',
    'profile.save': 'Imayaña',

    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.export_data': 'Yatiyawi Apsuña',
    'admin.export_excel': 'Excelaru Apsuña',
    'admin.export_excel_history': 'Excel: Nayra',
    'admin.export_csv_history': 'CSV: Nayra',
    'admin.export_excel_30': 'Excel: 30 Uru',
    'admin.export_csv_30': 'CSV: 30 Uru',
    'admin.export_excel_verified': 'Excel: Iyawsata',
    'admin.export_csv_verified': 'CSV: Iyawsata',
    'admin.total_reports': 'Taqpacha Yatiyawinaka',
    'admin.verified_reports': 'Iyawsata Yatiyawinaka',
    'admin.pending_redemptions': 'Turkaña Suyaskiri',
    'admin.users': 'Apnaqirinaka',
    'admin.messages': 'Yatiyawinaka',
    'admin.frequency_type': 'Uywa Uñjat (30d)',
    'admin.heatmap_history': 'Junt\'u Mapa (Nayra)',
    'admin.heatmap_30': 'Junt\'u Mapa (30 uru)',
    'admin.pending_reports': 'Yatiyawinaka Suyaskiri',
    'admin.verified_reports_30': 'Iyawsata (30d)',
    'admin.redemption_requests': 'Turkaña Mayiwinaka',
    'admin.user_management': 'Apnaqirinaka Uñjaña',
    'admin.report_history': 'Yatiyawi Sarnaqawi',
    'admin.view_pending': 'Suyaskiri Uñjaña',
    'admin.make_admin': 'Admin Luraña',
    'admin.remove_admin': 'Admin Apsuña',
    'admin.approve': 'Iyawsña',
    'admin.reject': 'Janiw Saña',
    'admin.status_pending': 'Suyaskiri',
    'admin.status_approved': 'Iyawsata',
    'admin.status_rejected': 'Janiw Sata',
    'admin.status_verified': 'Iyawsata',
    'admin.status_denied': 'Janiw Katuqata',
    'admin.user': 'Apnaqiri',
    'admin.contact': 'Yatiyawi',
    'admin.date': 'Uru',
    'admin.notes': 'Qillqatanaka',
    'admin.anonymous': 'Jan Sutini',

    'onboarding.skip': 'Pasayaña',
    'onboarding.next': 'Jutiri',
    'onboarding.start': 'Qalltaña',
    'onboarding.slide1_title': 'Ratuki yatiyaña',
    'onboarding.slide1_desc': 'Kawkir uywsa uñjta, uka llawq\'aña.',
    'onboarding.slide2_title': 'Kawkhansa ukat Uñachayaña',
    'onboarding.slide2_desc': 'GPS kikinmanta jist\'arasi. Ma foto apsuñamawa.',
    'onboarding.slide3_title': '¿Jan señal utjiti?\nJaniw kuna llakisa.',
    'onboarding.slide3_desc': 'Coex5.0 yatiyawinaka imayi ukat internet utjipan khiti.',
    'onboarding.slide4_title': 'Gana Beneficios',
    'onboarding.slide4_desc': 'Sapa yatiyaña 10 puntos churi. 150 phuqhata, Especialista regalo churätam!',
    'onboarding.reward_label': 'Especialista Regalo',
    'onboarding.points_label': 'pts',
    'onboarding.offline_label': 'Jan internetani',
    'onboarding.saved_label': 'Akan imata',

    // Learn Section
    'learn.title': 'COEX5.0 WAN YATIQAÑA',
    'learn.subtitle': 'Yatiqaña askichañataki, sarnaqawinaka ukat kamachinaka.',
    'learn.search_placeholder': 'Guíanaka, videonaka, yatiyawinaka thaqhaña...',
    'learn.categories': 'Categoríanaka',
    'learn.no_guides': 'Janiw yatiyawinaka utjkiti.',
    'learn.no_saved': 'Janiw imat yatiyawinaka utjkiti.',
    'learn.saved_offline': 'Imata (Offline)',
    'learn.saved_count': '{count} yatiyawinaka',
    'learn.share': 'Lakiraña',
    'learn.consult': 'Jiskt\'aña',
    'learn.contact_specialist': 'Especialistampi rimay',
    'learn.your_name': 'Sutima',
    'learn.contact_info': 'Yatiyawi',
    'learn.reference': 'Referencia',
    'learn.query_label': '¿Kuna jiskt\'awima utji?',
    'learn.query_placeholder': 'Akan jiskt\'awima qillqam...',
    'learn.send_query': 'Jiskt\'awi Khitaña',
    'learn.sending': 'Khitaskta...',
    'learn.read_time': '{time} min',
    'learn.attachments': 'Imata Archivo',
    'learn.video': 'Video',
    'learn.image': 'Imagen',
    'learn.file': 'Archivo',
    'learn.link': 'Enlace',
    'learn.offline_warning': 'Offline: Imatanaka uñjasi.',
    'learn.save_for_offline': 'Jan internetani uñjañataki imaña',
    'learn.saved_success': 'Guía imata jan internetani uñjañataki',
    'learn.removed_success': 'Guía imatata apsuta',

    // Editor Section
    'editor.title': 'Yatiyawi Editor',
    'editor.groups': 'Tamachanaknaka',
    'editor.guides': 'Guíanaka',
    'editor.create_group': 'Machaq Tamachaña Luraña',
    'editor.edit_group': 'Tamachaña Askichaña',
    'editor.group_name': 'Tamachaña Suti',
    'editor.group_icon': 'Tamachaña Icono',
    'editor.save': 'Imayaña',
    'editor.cancel': 'Janiwa',
    'editor.create_guide': 'Machaq Guía Luraña',
    'editor.edit_guide': 'Guía Askichaña',
    'editor.guide_title': 'Guía Suti',
    'editor.guide_subtitle': 'Suti / Jisk\'a Yatiyawi',
    'editor.guide_group': 'Tamachaña / Categoría',
    'editor.guide_read_time': 'Uñjañataki Tiempo (min)',
    'editor.guide_image': 'Imagen URL',
    'editor.guide_video': 'Video URL (Youtube/Vimeo)',
    'editor.guide_content': 'Guía Yatiyawipa',
    'editor.preview': 'Uñjaña',
    'editor.publish': 'Guía Publicaña',
    'editor.delete_confirm': '¿Cheqapuniw apsuña muntati?',
    'editor.no_groups': 'Janiw tamachanaknaka utjkiti.',
    'editor.no_guides': 'Janiw guíanaka utjkiti.',
    'editor.add_video_url': 'Video URL Uchaña',
    'editor.add_image_url': 'Imagen URL Uchaña',
    'editor.add_file': 'Archivo Uchaña',
    'editor.add_link': 'Enlace Uchaña',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: { [key: string]: string | number }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('coex5_language') as Language;
    if (savedLanguage && ['es', 'en', 'pt', 'qu', 'ay'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('coex5_language', lang);
  };

  const t = (key: string, params?: { [key: string]: string | number }) => {
    const text = translations[language][key] || translations['es'][key] || key;
    if (params) {
      return Object.entries(params).reduce((acc, [k, v]) => {
        return acc.replace(`{${k}}`, String(v));
      }, text);
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
